DROP TABLE IF EXISTS PRICES;  
CREATE TABLE PRICES (
    PRICE_LIST   NUMBER      NOT NULL AUTO_INCREMENT,
    BRAND_ID NUMBER  NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRIORITY NUMBER NOT NULL,
    PRICE NUMBER NOT NULL,
    CURR VARCHAR('3') NOT NULL,
    PRIMARY KEY (PRICE_LIST)
);